### ISSUE TITLE
Commercial Licence

### ISSUE THREAD

**Issue by Kiliandeca** [Franckyi/Flushcraft#1]
Hi Franck,

It's Kilian we work at the same company and the same school, is this script free to use for commercial purposes? 

Have a great day :flushed:

**Comment by skyecodes** [comment]
nah fuck off 😳😳😳

**Comment by Kiliandeca** [comment]
Alright then..

![image](https://user-images.githubusercontent.com/20646200/103576956-368a5200-4ed4-11eb-9a3a-c96d6312e017.png)
